### ISSUE TITLE
Unable to register DID to Von Network

### ISSUE THREAD

**Issue by Yukuro** [ldej/go-acapy-client#1]
hi

When I ran the Example described in README.md, I got the following error
```
json: cannot unmarshal number into Go value of type acapy.RegisterDIDResponse
```

After debugging, I found the following error when registering a DID to the Von network
```
405 Method Not Allow
```

**Comment by ldej** [comment]
@Yukuro  Thank you so much. I didn't expect anybody to use this already :) I'm working on adding the present-proof v2 apis but I'm considering reorganising the whole repo.
